
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-emailservice
  namespace: elasticsearch
  labels:
    app: logstash-emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash-emailservice
  template:
    metadata:
      labels:
        app: logstash-emailservice
    spec:
      tolerations:
        - key: "node.cloudprovider.kubernetes.io/uninitialized"
          operator: "Exists"
          effect: "NoSchedule"

      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.12.0
          args: ["--config.reload.automatic"]
          env:
            - name: ELASTIC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: username
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elastic-credentials
                  key: password
          ports:
            - containerPort: 5044
            - containerPort: 9600
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: config-volume
              mountPath: /usr/share/logstash/config/pipelines.yml
              subPath: pipelines.yml
            - name: pipelines
              mountPath: /usr/share/logstash/pipeline/emailservice_pipeline.conf
              subPath: emailservice_pipeline.conf
            - name: itil-logs
              mountPath: /itil/logs
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: logstash-emailservice-config
        - name: pipelines
          configMap:
            name: logstash-emailservice-pipelines
        - name: itil-logs
          hostPath:
            path: /itil/logs
            type: DirectoryOrCreate
